name: cnes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - numpy
  - scipy
  - pandas
  - matplotlib
  - folium
  - pillow
  - geopandas
  - sentinelsat
  - utm
  - rasterio
  - seaborn
  - earthengine-api
  - scikit-image
  - notebook
  - opencv
  - cdsapi
  - xarray
  - bottleneck
  - dask
  - netcdf4
  - beautifulsoup4
  - ipyleaflet
  - cdsapi
  - pywin32=225
  - rtree=0.9.3
